### ISSUE TITLE
InternalInterface exception

### ISSUE THREAD

**Issue by alfs** [MONROE-PROJECT/Experiments#24]
I tried running the container (schedule 15065/520225), and get this error in the container log file:

```
2017-12-07T13:19:38.992915150Z Traceback (most recent call last):
2017-12-07T13:19:38.993173968Z   File "/opt/monroe/experiment.py", line 282, in <module>
2017-12-07T13:19:38.993263456Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.993305013Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.993340203Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.993374700Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.993702191Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.993739892Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.993773378Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.993806285Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.993839213Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.993872225Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.993905840Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.993939296Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.993972542Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.994005701Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.994424375Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.994463832Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.994497090Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.994531056Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.994564665Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.994597776Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.994631235Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.994664063Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.994697168Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.994730996Z Trying to get metadata for Telenor SE
2017-12-07T13:19:38.994980957Z     ifname = meta_info['modem']['InternalInterface']
2017-12-07T13:19:38.995118324Z   File "<string>", line 2, in __getitem__
2017-12-07T13:19:38.995158720Z   File "/usr/lib/python2.7/multiprocessing/managers.py", line 774, in _callmethod
2017-12-07T13:19:38.995196112Z     raise convert_to_error(kind, result)
2017-12-07T13:19:38.995231338Z KeyError: 'InternalInterface'
```

**Comment by jonakarl** [comment]
What experiment did you try to run, template?
